### PR TITLE
improve wording and appearance of theories.md

### PR DESCRIPTION
**Pull request by kkilobyte**
you suck at writing..,.,.,.,

### CODE REVIEW

**Comment by kelpseastem** [comment]
can confirm!

**Comment by kkilobyte** [comment]
write better next time smh my head,.,,.,,.,

**Comment by kelpseastem** [comment]
ill just have you write the docs or something lol

**Comment by kkilobyte** [comment]
nah you'll just write the next and ill improve it if i feel like it

**Comment by kelpseastem** [comment]
im trying to invite you to kuromuiroha please make an interview ticket

**Comment by kkilobyte** [comment]
oh ok sure one moment

**Pull request merged**
